from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
SRC = WEB / "src"
APP = SRC / "app"

ROUTES = {
    "/": APP / "page.tsx",
    "/rankings": APP / "rankings" / "page.tsx",
    "/portfolio": APP / "portfolio" / "page.tsx",
    "/methodology": APP / "methodology" / "page.tsx",
    "/candidates": APP / "candidates" / "page.tsx",
    "/architecture": APP / "architecture" / "page.tsx",
    "/research": APP / "research" / "page.tsx",
    "/research/performance": APP / "research" / "performance" / "page.tsx",
    "/research/experiments": APP / "research" / "experiments" / "page.tsx",
    "/about": APP / "about" / "page.tsx",
    "/disclosures": APP / "disclosures" / "page.tsx",
}

ALLOWED_INTERNAL = set(ROUTES) | {
    "/data/release_snapshot.json",
    "/data/forward_paper_snapshot.json",
    "/data/release_rankings_snapshot.json",
    "/data/candidate_funnel_snapshot.json",
    "/data/hypothetical_account_snapshot.json",
    "/data/crisis_diversifier_research.json",
    "/data/drawdown_budget_research.json",
    "/salarium-mark.svg",
    "/salarium-edge-glyph.svg",
    "/salarium-logo.svg",
    "/salarium-mark-light.svg",
    "/salarium-mark-dark.svg",
    "/manifest.webmanifest",
    "/robots.txt",
    "/sitemap.xml",
    "/opengraph-image",
}


def text_files() -> list[Path]:
    return [
        path
        for path in sorted(SRC.rglob("*"))
        if path.is_file() and path.suffix in {".ts", ".tsx", ".css"}
    ]


def source_text() -> str:
    return "\n".join(path.read_text(encoding="utf-8", errors="ignore") for path in text_files())


def test_all_public_routes_exist_and_identify_main_content() -> None:
    for route, path in ROUTES.items():
        assert path.is_file(), f"Missing route {route}: {path}"
        assert 'id="main-content"' in path.read_text(encoding="utf-8"), f"Route {route} lacks the skip-link target"


def test_navigation_and_footer_reach_every_public_route() -> None:
    config = (SRC / "lib" / "site-config.ts").read_text(encoding="utf-8")
    for route in ["/", "/rankings", "/portfolio", "/methodology", "/candidates", "/architecture", "/research", "/research/performance", "/research/experiments", "/about"]:
        assert f'href: "{route}"' in config
    footer = (SRC / "components" / "site-footer.tsx").read_text(encoding="utf-8")
    assert 'href="/disclosures"' in footer


def test_no_placeholder_dead_or_legacy_release_markers() -> None:
    text = source_text()
    forbidden = {
        'href="#"': "placeholder hash link",
        'href=""': "empty link",
        "javascript:": "javascript link",
        "Create Next App": "starter metadata",
        "Generated by create next app": "starter description",
        "TODO": "unfinished TODO",
        "FIXME": "unfinished FIXME",
        "coming soon": "unfinished copy",
        "Coming soon": "unfinished copy",
        "Solarium": "legacy product branding",
        "SOLARIUM": "legacy product branding",
    }
    for token, description in forbidden.items():
        assert token not in text, f"Found {description}: {token}"


def test_literal_internal_links_target_governed_destinations() -> None:
    violations: list[str] = []
    pattern = re.compile(r'(?:href|canonical)\s*[:=]\s*(?:\{\s*)?["\'](/[^"\']*)["\']')
    for path in text_files():
        text = path.read_text(encoding="utf-8", errors="ignore")
        for match in pattern.finditer(text):
            href = match.group(1).split("?", 1)[0].split("#", 1)[0] or "/"
            if href not in ALLOWED_INTERNAL:
                violations.append(f"{path.relative_to(ROOT)} -> {match.group(1)}")
    assert not violations, "Unresolved internal links:\n" + "\n".join(violations)


def test_every_button_has_a_real_click_handler() -> None:
    violations: list[str] = []
    pattern = re.compile(r"<button\b[^>]*>", flags=re.DOTALL)
    for path in text_files():
        text = path.read_text(encoding="utf-8", errors="ignore")
        for match in pattern.finditer(text):
            if "onClick=" not in match.group(0):
                violations.append(f"{path.relative_to(ROOT)}: {match.group(0)[:140]}")
    assert not violations, "Buttons without handlers:\n" + "\n".join(violations)


def test_website_has_complete_automated_release_gate() -> None:
    package = json.loads((WEB / "package.json").read_text(encoding="utf-8"))
    scripts = package["scripts"]
    for key in ["dev", "build", "start", "lint", "validate:site", "smoke", "release:check", "check:deployment"]:
        assert scripts.get(key), f"Missing web script: {key}"
    assert "validate:site" in scripts["release:check"]
    assert "build" in scripts["release:check"]
    assert "smoke" in scripts["release:check"]
    assert (WEB / "scripts" / "validate-site.mjs").is_file()
    assert (WEB / "scripts" / "smoke-site.mjs").is_file()
    assert (WEB / "scripts" / "check-deployment.mjs").is_file()
    assert (ROOT / "docs" / "SALARIUM_1_0_MODEL_CARD.md").is_file()
    assert (ROOT / "docs" / "RELEASE_NOTES_1_0.md").is_file()


def test_release_metadata_discovery_error_and_loading_surfaces_exist() -> None:
    for path in [
        APP / "layout.tsx",
        APP / "manifest.ts",
        APP / "robots.ts",
        APP / "sitemap.ts",
        APP / "opengraph-image.tsx",
        APP / "not-found.tsx",
        APP / "error.tsx",
        APP / "loading.tsx",
        WEB / "public" / "salarium-mark.svg",
        WEB / "public" / "data" / "hypothetical_account_snapshot.json",
        WEB / "public" / "data" / "crisis_diversifier_research.json",
        WEB / "public" / "data" / "drawdown_budget_research.json",
        WEB / "public" / "data" / "forward_paper_snapshot.json",
    ]:
        assert path.is_file(), f"Missing production web artifact: {path.relative_to(ROOT)}"

    layout = (APP / "layout.tsx").read_text(encoding="utf-8")
    assert "Autonomous Investment Research" in layout
    assert "application/ld+json" in layout
    assert "SiteHeader" in layout and "SiteFooter" in layout
    assert 'href="#main-content"' in layout


def test_hypothetical_account_is_governed_by_the_release_evidence() -> None:
    account = json.loads((WEB / "public" / "data" / "hypothetical_account_snapshot.json").read_text(encoding="utf-8"))
    release = json.loads((WEB / "public" / "data" / "release_snapshot.json").read_text(encoding="utf-8"))
    core = release["results"]["core_balanced"]

    assert account["schema_version"] == "1.1"
    assert account["currency"] == "USD"
    assert account["starting_balance"] == 100_000
    assert account["ending_balance"] == account["points"][-1]["value"]
    assert account["benchmark"]["ticker"] == "SPY"
    assert account["benchmark"]["data_provider"] == "Yahoo adjusted-close proxy history"
    assert account["benchmark"]["starting_balance"] == 100_000
    assert account["benchmark"]["ending_balance"] == account["points"][-1]["benchmark_value"]
    assert account["benchmark"]["statistics"]["annualized_total_return"] > 0
    assert account["benchmark"]["statistics"]["max_drawdown"] < 0
    assert account["points"][0]["value"] == 100_000
    assert account["points"][0]["benchmark_value"] == 100_000
    assert account["period"] == {"start": account["points"][0]["date"], "end": account["points"][-1]["date"]}
    assert len(account["points"]) == core["num_rebalances"] + 1
    assert core["num_rebalances"] == account["statistics"]["rebalances"]
    assert [point["date"] for point in account["points"]] == sorted(point["date"] for point in account["points"])
    assert all(point["value"] > 0 and point["benchmark_value"] > 0 for point in account["points"])
    for metric in ["annualized_net_return", "net_sharpe", "max_drawdown"]:
        assert account["statistics"][metric] == core[metric]
    for key in ["base_policy", "exposure_policy", "risk_anchor", "signal_blend"]:
        assert account["model"][key] == core[key]
    assert account["model"]["horizon_days"] == release["architecture"]["model_horizon_days"]
    assert account["model"]["rebalance_every_days"] == release["architecture"]["rebalance_every_days"]
    assert account["governance"]["hypothetical"] is True
    assert account["governance"]["live"] is False
    assert account["governance"]["modeled_costs_included"] is True
    assert account["governance"]["taxes_and_market_impact_excluded"] is True
    assert account["governance"]["benchmark_is_market_proxy"] is True
    assert account["governance"]["benchmark_fund_expenses_and_distributions_reflected_in_adjusted_close"] is True
    assert account["governance"]["benchmark_initial_trade_cost_excluded"] is True
    assert account["provenance"]["source_sha256"] == hashlib.sha256(
        (ROOT / account["provenance"]["source_path"]).read_bytes()
    ).hexdigest()
    assert account["provenance"]["benchmark_source_sha256"] == hashlib.sha256(
        (ROOT / account["provenance"]["benchmark_source_path"]).read_bytes()
    ).hexdigest()


def test_forward_paper_snapshot_is_current_governed_and_non_executing() -> None:
    forward = json.loads(
        (WEB / "public" / "data" / "forward_paper_snapshot.json").read_text(
            encoding="utf-8"
        )
    )
    state = json.loads(
        (ROOT / "reports" / "shadow" / "drawdown_budget_shadow_state.json").read_text(
            encoding="utf-8"
        )
    )
    model_manifest = json.loads(
        (ROOT / "artifacts" / "models" / "salarium_20d_forward_model_manifest.json").read_text(
            encoding="utf-8"
        )
    )
    rows = forward["latest_signal_state"]["rankings"]
    assert forward["schema_version"] == "1.0"
    assert forward["system"]["status"] == "forward_paper_no_orders"
    assert forward["latest_signal_state"]["date"] >= "2026-08-11"
    assert len(rows) == forward["latest_signal_state"]["count"] == 25
    assert forward["latest_signal_state"]["universe_count"] >= 475
    assert [row["rank"] for row in rows] == list(range(1, 26))
    assert [row["score"] for row in rows] == sorted(
        [row["score"] for row in rows], reverse=True
    )
    assert forward["model"]["daily_retraining"] is False
    assert forward["model"]["target_horizon_days"] == 20
    assert forward["model"]["model_sha256"] == model_manifest["model_sha256"]
    assert hashlib.sha256(
        (ROOT / model_manifest["model_path"]).read_bytes()
    ).hexdigest() == model_manifest["model_sha256"]
    assert forward["data_quality"]["passed"] is True
    assert forward["data_quality"]["feature_coverage"] >= 0.95
    assert forward["forward_portfolio"]["last_rebalance_date"] == state["last_rebalance_date"]
    assert len(forward["forward_portfolio"]["holdings"]) == 10
    assert sum(
        holding["paper_weight"]
        for holding in forward["forward_portfolio"]["holdings"]
    ) == pytest.approx(forward["forward_portfolio"]["shadow_equity_exposure"])
    for key in [
        "paper_only",
        "append_only_ledger",
        "canonical_release_unchanged",
    ]:
        assert forward["governance"][key] is True
    for key in [
        "historical_backfill",
        "live_capital",
        "brokerage_connection",
        "order_generation",
        "order_submission",
        "automatic_model_retraining",
    ]:
        assert forward["governance"][key] is False

    ledger = (ROOT / "reports" / "shadow" / "drawdown_budget_shadow_ledger.csv").read_text(
        encoding="utf-8"
    ).splitlines()
    assert len(ledger) >= 2
    assert "initialized_no_market_outcome" in ledger[1]
    rebalance_dates = [row.split(",")[1] for row in ledger[1:]]
    assert rebalance_dates == sorted(set(rebalance_dates))


def test_crisis_diversifier_research_preserves_failed_gate_verdict() -> None:
    crisis = json.loads((WEB / "public" / "data" / "crisis_diversifier_research.json").read_text(encoding="utf-8"))
    release = json.loads((WEB / "public" / "data" / "release_snapshot.json").read_text(encoding="utf-8"))
    core = release["results"]["core_balanced"]
    baseline = next(row for row in crisis["overall"] if row["policy"] == "official_baseline" and row["period"] == "overall")

    assert crisis["schema_version"] == "1.0"
    assert crisis["experiment"]["status"] == "research_candidate"
    assert crisis["period"]["rebalances"] == core["num_rebalances"] == 139
    assert crisis["comparator"] == "baseline_cash_yield"
    assert crisis["verdict"]["promotion"] is False
    assert crisis["verdict"]["promoted_policies"] == []
    assert len(crisis["acceptance"]) == 24
    assert not any(row["all_gates_pass"] for row in crisis["acceptance"])
    assert len(crisis["robustness"]) == 96
    assert len(crisis["bootstrap"]) == 6
    assert len(crisis["stress_windows"]) == 40
    for metric in ["annualized_net_return", "net_sharpe", "max_drawdown"]:
        assert abs(baseline[metric] - core[metric]) <= 1e-12
    for key in ["config_sha256", "baseline_source_sha256", "proxy_report_sha256"]:
        assert re.fullmatch(r"[a-f0-9]{64}", crisis["provenance"][key])
    for path_key, hash_key in [
        ("config", "config_sha256"),
        ("baseline_source", "baseline_source_sha256"),
        ("proxy_report", "proxy_report_sha256"),
    ]:
        source = ROOT / crisis["provenance"][path_key]
        assert source.is_file()
        assert hashlib.sha256(source.read_bytes()).hexdigest() == crisis["provenance"][hash_key]


def test_drawdown_budget_candidate_meets_target_without_claiming_release_promotion() -> None:
    research = json.loads((WEB / "public" / "data" / "drawdown_budget_research.json").read_text(encoding="utf-8"))

    assert research["schema_version"] == "1.0"
    assert research["experiment"]["status"] == "validated_research_candidate"
    assert research["experiment"]["confirmation_segment_pristine"] is False
    assert research["period"]["rebalances"] == 139
    assert research["acceptance"]["all_gates_pass"] is True
    assert research["acceptance"]["overall_max_drawdown"] >= -0.25
    assert research["acceptance"]["development_max_drawdown"] >= -0.25
    assert research["acceptance"]["confirmation_max_drawdown"] >= -0.25
    assert research["acceptance"]["parameter_neighborhood_pass_rate"] == 1.0
    assert research["bootstrap"]["candidate_max_drawdown_probability_below_25pct"] >= 0.95
    assert research["verdict"]["research_target_achieved"] is True
    assert research["verdict"]["promotion"] is False
    assert research["verdict"]["status"] == "validated_candidate"
    assert research["verdict"]["independent_holdout_available"] is False
    assert research["verdict"]["explicit_release_approval"] is False
    assert research["verdict"]["shadow_mandate_approved"] is True
    assert research["verdict"]["explicit_shadow_approval"] is True
    assert research["verdict"]["soft_floor_is_not_a_guarantee"] is True
    shadow = research["shadow_mandate"]
    assert shadow["mandate"]["status"] == "approved_awaiting_first_eligible_snapshot"
    assert shadow["mandate"]["approval_scope"] == "shadow_paper_tracking_only"
    assert shadow["mandate"]["paper_notional_usd"] == 100_000
    assert shadow["activation"]["historical_backfill_permitted"] is False
    assert shadow["activation"]["current_status"] == "awaiting_first_forward_observation"
    assert shadow["execution"]["live_capital"] is False
    assert shadow["execution"]["brokerage_connection"] is False
    assert shadow["execution"]["order_generation"] is False
    assert shadow["execution"]["order_submission"] is False
    assert shadow["execution"]["canonical_release_unchanged"] is True
    assert shadow["promotion"]["automatic_promotion"] is False
    assert shadow["ledger"]["observations"] == 0
    for path_key, hash_key in [
        ("config", "config_sha256"),
        ("shadow_mandate_config", "shadow_mandate_config_sha256"),
        ("baseline_source", "baseline_source_sha256"),
        ("cash_proxy_report", "cash_proxy_report_sha256"),
        ("result_path", "result_sha256"),
    ]:
        source = ROOT / research["provenance"][path_key]
        assert source.is_file()
        assert hashlib.sha256(source.read_bytes()).hexdigest() == research["provenance"][hash_key]


def test_security_headers_and_dynamic_production_url_are_configured() -> None:
    next_config = (WEB / "next.config.ts").read_text(encoding="utf-8")
    for header in ["X-Content-Type-Options", "X-Frame-Options", "Referrer-Policy", "Permissions-Policy"]:
        assert header in next_config

    site_config = (SRC / "lib" / "site-config.ts").read_text(encoding="utf-8")
    assert "NEXT_PUBLIC_SITE_URL" in site_config
    assert "VERCEL_PROJECT_PRODUCTION_URL" in site_config
    assert "VERCEL_URL" in site_config
    assert "salarium-ten.vercel.app" not in site_config


def test_mobile_navigation_is_real_interaction() -> None:
    header = (SRC / "components" / "site-header.tsx").read_text(encoding="utf-8")
    assert 'aria-controls="mobile-navigation"' in header
    assert "onClick={() => setOpen" in header
    assert 'id="mobile-navigation"' in header
    assert 'event.key === "Escape"' in header
