from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
SRC = WEB / "src"
APP = SRC / "app"

ROUTES = {
    "/": APP / "page.tsx",
    "/rankings": APP / "rankings" / "page.tsx",
    "/portfolio": APP / "portfolio" / "page.tsx",
    "/methodology": APP / "methodology" / "page.tsx",
    "/candidates": APP / "candidates" / "page.tsx",
    "/architecture": APP / "architecture" / "page.tsx",
    "/research": APP / "research" / "page.tsx",
    "/research/performance": APP / "research" / "performance" / "page.tsx",
    "/research/experiments": APP / "research" / "experiments" / "page.tsx",
    "/about": APP / "about" / "page.tsx",
    "/disclosures": APP / "disclosures" / "page.tsx",
}

ALLOWED_INTERNAL = set(ROUTES) | {
    "/data/release_snapshot.json",
    "/data/release_rankings_snapshot.json",
    "/data/candidate_funnel_snapshot.json",
    "/salarium-mark.svg",
    "/salarium-edge-glyph.svg",
    "/salarium-logo.svg",
    "/salarium-mark-light.svg",
    "/salarium-mark-dark.svg",
    "/manifest.webmanifest",
    "/robots.txt",
    "/sitemap.xml",
    "/opengraph-image",
}


def text_files() -> list[Path]:
    return [
        path
        for path in sorted(SRC.rglob("*"))
        if path.is_file() and path.suffix in {".ts", ".tsx", ".css"}
    ]


def source_text() -> str:
    return "\n".join(path.read_text(encoding="utf-8", errors="ignore") for path in text_files())


def test_all_public_routes_exist_and_identify_main_content() -> None:
    for route, path in ROUTES.items():
        assert path.is_file(), f"Missing route {route}: {path}"
        assert 'id="main-content"' in path.read_text(encoding="utf-8"), f"Route {route} lacks the skip-link target"


def test_navigation_and_footer_reach_every_public_route() -> None:
    config = (SRC / "lib" / "site-config.ts").read_text(encoding="utf-8")
    for route in ["/", "/rankings", "/portfolio", "/methodology", "/candidates", "/architecture", "/research", "/research/performance", "/research/experiments", "/about"]:
        assert f'href: "{route}"' in config
    footer = (SRC / "components" / "site-footer.tsx").read_text(encoding="utf-8")
    assert 'href="/disclosures"' in footer


def test_no_placeholder_dead_or_legacy_release_markers() -> None:
    text = source_text()
    forbidden = {
        'href="#"': "placeholder hash link",
        'href=""': "empty link",
        "javascript:": "javascript link",
        "Create Next App": "starter metadata",
        "Generated by create next app": "starter description",
        "TODO": "unfinished TODO",
        "FIXME": "unfinished FIXME",
        "coming soon": "unfinished copy",
        "Coming soon": "unfinished copy",
        "Solarium": "legacy product branding",
        "SOLARIUM": "legacy product branding",
    }
    for token, description in forbidden.items():
        assert token not in text, f"Found {description}: {token}"


def test_literal_internal_links_target_governed_destinations() -> None:
    violations: list[str] = []
    pattern = re.compile(r'(?:href|canonical)\s*[:=]\s*(?:\{\s*)?["\'](/[^"\']*)["\']')
    for path in text_files():
        text = path.read_text(encoding="utf-8", errors="ignore")
        for match in pattern.finditer(text):
            href = match.group(1).split("?", 1)[0].split("#", 1)[0] or "/"
            if href not in ALLOWED_INTERNAL:
                violations.append(f"{path.relative_to(ROOT)} -> {match.group(1)}")
    assert not violations, "Unresolved internal links:\n" + "\n".join(violations)


def test_every_button_has_a_real_click_handler() -> None:
    violations: list[str] = []
    pattern = re.compile(r"<button\b[^>]*>", flags=re.DOTALL)
    for path in text_files():
        text = path.read_text(encoding="utf-8", errors="ignore")
        for match in pattern.finditer(text):
            if "onClick=" not in match.group(0):
                violations.append(f"{path.relative_to(ROOT)}: {match.group(0)[:140]}")
    assert not violations, "Buttons without handlers:\n" + "\n".join(violations)


def test_website_has_complete_automated_release_gate() -> None:
    package = json.loads((WEB / "package.json").read_text(encoding="utf-8"))
    scripts = package["scripts"]
    for key in ["dev", "build", "start", "lint", "validate:site", "smoke", "release:check", "check:deployment"]:
        assert scripts.get(key), f"Missing web script: {key}"
    assert "validate:site" in scripts["release:check"]
    assert "build" in scripts["release:check"]
    assert "smoke" in scripts["release:check"]
    assert (WEB / "scripts" / "validate-site.mjs").is_file()
    assert (WEB / "scripts" / "smoke-site.mjs").is_file()
    assert (WEB / "scripts" / "check-deployment.mjs").is_file()
    assert (ROOT / "docs" / "SALARIUM_1_0_MODEL_CARD.md").is_file()
    assert (ROOT / "docs" / "RELEASE_NOTES_1_0.md").is_file()


def test_release_metadata_discovery_error_and_loading_surfaces_exist() -> None:
    for path in [
        APP / "layout.tsx",
        APP / "manifest.ts",
        APP / "robots.ts",
        APP / "sitemap.ts",
        APP / "opengraph-image.tsx",
        APP / "not-found.tsx",
        APP / "error.tsx",
        APP / "loading.tsx",
        WEB / "public" / "salarium-mark.svg",
    ]:
        assert path.is_file(), f"Missing production web artifact: {path.relative_to(ROOT)}"

    layout = (APP / "layout.tsx").read_text(encoding="utf-8")
    assert "Autonomous Investment Research" in layout
    assert "application/ld+json" in layout
    assert "SiteHeader" in layout and "SiteFooter" in layout
    assert 'href="#main-content"' in layout


def test_security_headers_and_dynamic_production_url_are_configured() -> None:
    next_config = (WEB / "next.config.ts").read_text(encoding="utf-8")
    for header in ["X-Content-Type-Options", "X-Frame-Options", "Referrer-Policy", "Permissions-Policy"]:
        assert header in next_config

    site_config = (SRC / "lib" / "site-config.ts").read_text(encoding="utf-8")
    assert "NEXT_PUBLIC_SITE_URL" in site_config
    assert "VERCEL_PROJECT_PRODUCTION_URL" in site_config
    assert "VERCEL_URL" in site_config
    assert "salarium-ten.vercel.app" not in site_config


def test_mobile_navigation_is_real_interaction() -> None:
    header = (SRC / "components" / "site-header.tsx").read_text(encoding="utf-8")
    assert 'aria-controls="mobile-navigation"' in header
    assert "onClick={() => setOpen" in header
    assert 'id="mobile-navigation"' in header
    assert 'event.key === "Escape"' in header
