import fs from "node:fs";
import crypto from "node:crypto";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "src");
const DATA = path.join(ROOT, "public", "data");

const ROUTES = new Map([
  ["/", "src/app/page.tsx"],
  ["/rankings", "src/app/rankings/page.tsx"],
  ["/portfolio", "src/app/portfolio/page.tsx"],
  ["/simulation", "src/app/simulation/page.tsx"],
  ["/methodology", "src/app/methodology/page.tsx"],
  ["/candidates", "src/app/candidates/page.tsx"],
  ["/architecture", "src/app/architecture/page.tsx"],
  ["/research", "src/app/research/page.tsx"],
  ["/research/performance", "src/app/research/performance/page.tsx"],
  ["/research/experiments", "src/app/research/experiments/page.tsx"],
  ["/about", "src/app/about/page.tsx"],
  ["/disclosures", "src/app/disclosures/page.tsx"],
]);
const PRIMARY_NAV_ROUTES = ["/rankings", "/portfolio", "/simulation", "/research", "/methodology", "/architecture", "/about"];

const ALLOWED_INTERNAL = new Set([
  ...ROUTES.keys(),
  "/data/release_snapshot.json",
  "/data/forward_paper_snapshot.json",
  "/data/release_rankings_snapshot.json",
  "/data/candidate_funnel_snapshot.json",
  "/data/hypothetical_account_snapshot.json",
  "/data/crisis_diversifier_research.json",
  "/data/drawdown_budget_research.json",
  "/salarium-mark.svg",
  "/salarium-edge-glyph.svg",
  "/salarium-logo.svg",
  "/salarium-roman-bust.png",
  "/salarium-mark-light.svg",
  "/salarium-mark-dark.svg",
  "/manifest.webmanifest",
  "/robots.txt",
  "/sitemap.xml",
  "/opengraph-image",
]);

const REQUIRED_ARTIFACTS = [
  "src/app/layout.tsx",
  "src/app/manifest.ts",
  "src/app/robots.ts",
  "src/app/sitemap.ts",
  "src/app/opengraph-image.tsx",
  "src/app/not-found.tsx",
  "src/app/error.tsx",
  "src/app/loading.tsx",
  "public/salarium-mark.svg",
  "public/salarium-edge-glyph.svg",
  "public/salarium-logo.svg",
  "public/salarium-roman-bust.png",
  "public/salarium-mark-light.svg",
  "public/salarium-mark-dark.svg",
  "public/data/release_snapshot.json",
  "public/data/forward_paper_snapshot.json",
  "public/data/release_rankings_snapshot.json",
  "public/data/candidate_funnel_snapshot.json",
  "public/data/hypothetical_account_snapshot.json",
  "public/data/crisis_diversifier_research.json",
  "public/data/drawdown_budget_research.json",
  "scripts/smoke-site.mjs",
  "scripts/check-deployment.mjs",
  "../docs/SALARIUM_1_0_MODEL_CARD.md",
  "../docs/RELEASE_NOTES_1_0.md",
];

const FORBIDDEN = [
  ["create next app", "starter scaffold"],
  ["generated by create next app", "starter scaffold"],
  ["href=\"#\"", "placeholder hash link"],
  ["href='#'", "placeholder hash link"],
  ["href=\"\"", "empty link"],
  ["href=''", "empty link"],
  ["javascript:", "javascript link"],
  ["lorem ipsum", "placeholder copy"],
  ["coming soon", "unfinished copy"],
  ["todo", "unfinished TODO"],
  ["fixme", "unfinished FIXME"],
  ["solarium", "legacy product branding"],
];

function walk(directory) {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(directory, entry.name);
    if (entry.isDirectory()) return walk(full);
    return [full];
  });
}

function read(relative) {
  return fs.readFileSync(path.join(ROOT, relative), "utf8");
}

function readJson(filename) {
  return JSON.parse(fs.readFileSync(path.join(DATA, filename), "utf8"));
}

function repositorySha256(relativePath) {
  return crypto.createHash("sha256").update(fs.readFileSync(path.resolve(ROOT, "..", relativePath))).digest("hex");
}

function relative(filename) {
  return path.relative(ROOT, filename).split(path.sep).join("/");
}

function normalizeInternal(raw) {
  const withoutHash = raw.split("#", 1)[0];
  return withoutHash.split("?", 1)[0] || "/";
}

const errors = [];

for (const [route, relativePage] of ROUTES) {
  const filename = path.join(ROOT, relativePage);
  if (!fs.existsSync(filename)) {
    errors.push(`Missing page for ${route}: ${relativePage}`);
    continue;
  }
  if (!fs.readFileSync(filename, "utf8").includes('id="main-content"')) {
    errors.push(`Route ${route} does not expose id=\"main-content\" for the skip link`);
  }
}

for (const artifact of REQUIRED_ARTIFACTS) {
  if (!fs.existsSync(path.join(ROOT, artifact))) errors.push(`Missing release artifact: ${artifact}`);
}

const sourceFiles = walk(SRC).filter((filename) => /\.(?:ts|tsx|css)$/.test(filename));
for (const filename of sourceFiles) {
  const text = fs.readFileSync(filename, "utf8");
  const lower = text.toLowerCase();

  for (const [token, label] of FORBIDDEN) {
    if (lower.includes(token)) errors.push(`${relative(filename)} contains ${label}: ${JSON.stringify(token)}`);
  }

  for (const match of text.matchAll(/(?:href|canonical)\s*[:=]\s*(?:\{\s*)?["'](\/[^"']*)["']/g)) {
    const destination = normalizeInternal(match[1]);
    if (!ALLOWED_INTERNAL.has(destination)) {
      errors.push(`${relative(filename)} links to an unresolved internal destination: ${match[1]}`);
    }
  }

  for (const match of text.matchAll(/<button\b[^>]*>/gs)) {
    if (!/\bonClick\s*=/.test(match[0])) {
      errors.push(`${relative(filename)} contains a button without an onClick handler: ${match[0].replace(/\s+/g, " ").slice(0, 160)}`);
    }
  }
}

const release = readJson("release_snapshot.json");
const ranking = readJson("release_rankings_snapshot.json");
const forward = readJson("forward_paper_snapshot.json");
const candidates = readJson("candidate_funnel_snapshot.json");
const account = readJson("hypothetical_account_snapshot.json");
const crisis = readJson("crisis_diversifier_research.json");
const drawdownBudget = readJson("drawdown_budget_research.json");

if (release.schema_version !== "1.1") errors.push(`Expected release schema 1.1; found ${release.schema_version}`);
const architecture = release.architecture ?? {};
const lockedArchitecture = {
  universe: "Liquid-500",
  model_horizon_days: 20,
  rebalance_every_days: 10,
  top_n: 10,
  buffer_rank: 15,
  covariance_lookback_days: 60,
  signal_blend: 0.25,
  leverage_cap: 1.25,
};
for (const [key, expected] of Object.entries(lockedArchitecture)) {
  if (architecture[key] !== expected) errors.push(`Release architecture ${key} is ${architecture[key]}; expected ${expected}`);
}
if (release.governance?.live_trading !== false) errors.push("Release must explicitly state that live trading is disabled");
if (release.governance?.investment_advice !== false) errors.push("Release must explicitly state that it is not investment advice");
if (!Array.isArray(release.research?.decisions) || release.research.decisions.length !== 6) {
  errors.push("Release decision ledger must contain six governed decisions");
}

if (ranking.schema_version !== "1.0") errors.push(`Expected ranking schema 1.0; found ${ranking.schema_version}`);
if (ranking.architecture?.universe !== "Liquid-500") errors.push("Release ranking universe is not Liquid-500");
if (ranking.architecture?.model_horizon_days !== 20) errors.push("Release rankings are not generated by the 20D model");
if (ranking.architecture?.rebalance_every_days !== 10) errors.push("Release ranking artifact does not declare the 10D rebalance cadence");
const rankingRows = ranking.latest_signal_state?.rankings ?? [];
if (ranking.latest_signal_state?.count !== rankingRows.length) errors.push("Release ranking count does not match the published row count");
if ((ranking.latest_signal_state?.universe_count ?? 0) < rankingRows.length) errors.push("Release ranking universe count is smaller than the published ranking list");
if (rankingRows.length !== 25) errors.push(`Expected 25 published release rankings; found ${rankingRows.length}`);
const ranks = rankingRows.map((row) => Number(row.rank));
if (ranks.some((value, index) => value !== index + 1)) errors.push("Release rankings are not numbered consecutively from 1");
const scores = rankingRows.map((row) => Number(row.score));
if (scores.some((value, index) => index > 0 && value > scores[index - 1])) errors.push("Release rankings are not sorted by descending score");

if (forward.schema_version !== "1.0") errors.push(`Expected forward-paper schema 1.0; found ${forward.schema_version}`);
if (forward.system?.status !== "forward_paper_no_orders") errors.push("Forward snapshot is not explicitly paper-only");
const forwardRows = forward.latest_signal_state?.rankings ?? [];
if (forward.latest_signal_state?.count !== forwardRows.length || forwardRows.length !== 25) errors.push("Forward snapshot must publish exactly 25 ranked rows");
if ((forward.latest_signal_state?.universe_count ?? 0) < 475) errors.push("Forward snapshot scored fewer than 95% of the governed universe");
if (forward.data_quality?.passed !== true || Number(forward.data_quality?.feature_coverage) < 0.95) errors.push("Forward data-quality gate did not pass");
if (forward.model?.target_horizon_days !== 20 || forward.model?.daily_retraining !== false) errors.push("Forward snapshot does not use the frozen 20D model contract");
if ((forward.forward_portfolio?.holdings ?? []).length !== 10) errors.push("Forward paper portfolio does not contain ten holdings");
const forwardPaperWeight = (forward.forward_portfolio?.holdings ?? []).reduce((sum, row) => sum + Number(row.paper_weight), 0);
if (Math.abs(forwardPaperWeight - Number(forward.forward_portfolio?.shadow_equity_exposure)) > 1e-10) errors.push("Forward paper weights do not sum to governed equity exposure");
for (const key of ["paper_only", "append_only_ledger", "canonical_release_unchanged"]) {
  if (forward.governance?.[key] !== true) errors.push(`Forward governance control ${key} must be true`);
}
for (const key of ["historical_backfill", "live_capital", "brokerage_connection", "order_generation", "order_submission", "automatic_model_retraining"]) {
  if (forward.governance?.[key] !== false) errors.push(`Forward governance control ${key} must be false`);
}
if (!/^[a-f0-9]{64}$/.test(forward.provenance?.model_sha256 ?? "")) errors.push("Forward model hash is missing or malformed");
if (!/^[a-f0-9]{64}$/.test(forward.provenance?.market_data_sha256 ?? "")) errors.push("Forward market-data hash is missing or malformed");

const candidateRows = candidates.candidates ?? [];
if (candidates.evidence_summary?.candidate_count !== candidateRows.length) errors.push("Candidate snapshot count does not match candidate rows");

const accountPoints = account.points ?? [];
const coreResult = release.results?.core_balanced ?? {};
if (account.schema_version !== "1.1") errors.push(`Expected hypothetical account schema 1.1; found ${account.schema_version}`);
if (account.currency !== "USD") errors.push("Hypothetical account is not denominated in USD");
if (account.starting_balance !== 100000) errors.push("Hypothetical account must begin with exactly $100,000");
if (account.ending_balance !== accountPoints.at(-1)?.value) errors.push("Hypothetical ending balance does not match the final chart point");
if (account.benchmark?.ticker !== "SPY") errors.push("Hypothetical account benchmark must be the governed SPY market proxy");
if (account.benchmark?.starting_balance !== 100000 || accountPoints[0]?.benchmark_value !== 100000) errors.push("Benchmark comparison must begin with exactly $100,000");
if (account.benchmark?.ending_balance !== accountPoints.at(-1)?.benchmark_value) errors.push("Benchmark ending balance does not match the final chart point");
if (!(account.benchmark?.statistics?.annualized_total_return > 0)) errors.push("Benchmark annualized return is missing or invalid");
if (!(account.benchmark?.statistics?.max_drawdown < 0)) errors.push("Benchmark maximum drawdown is missing or invalid");
if (accountPoints[0]?.value !== 100000) errors.push("Salarium chart must include its initial $100,000 observation");
if (accountPoints.length !== coreResult.num_rebalances + 1) errors.push("Hypothetical account observations must include one initial point plus every release holding interval");
if (account.statistics?.rebalances !== coreResult.num_rebalances) errors.push("Hypothetical account rebalance statistic is inconsistent with the release");
for (const key of ["annualized_net_return", "net_sharpe", "max_drawdown"]) {
  if (account.statistics?.[key] !== coreResult[key]) errors.push(`Hypothetical account ${key} is inconsistent with the core release result`);
}
for (const key of ["base_policy", "exposure_policy", "risk_anchor", "signal_blend"]) {
  if (account.model?.[key] !== coreResult[key]) errors.push(`Hypothetical account model ${key} is inconsistent with the core release result`);
}
if (account.model?.horizon_days !== architecture.model_horizon_days) errors.push("Hypothetical account horizon does not match the release architecture");
if (account.model?.rebalance_every_days !== architecture.rebalance_every_days) errors.push("Hypothetical account rebalance cadence does not match the release architecture");
if (account.period?.start !== accountPoints[0]?.date || account.period?.end !== accountPoints.at(-1)?.date) errors.push("Hypothetical account period does not match its chart points");
if (accountPoints.some((point, index) => index > 0 && point.date <= accountPoints[index - 1].date)) errors.push("Hypothetical account points are not in chronological order");
if (accountPoints.some((point) => !(point.value > 0) || !(point.benchmark_value > 0))) errors.push("Hypothetical account contains a non-positive Salarium or benchmark value");
if (account.governance?.hypothetical !== true || account.governance?.live !== false) errors.push("Hypothetical account must be explicitly labeled simulated and not live");
if (account.governance?.modeled_costs_included !== true) errors.push("Hypothetical account must declare modeled transaction costs");
if (account.governance?.taxes_and_market_impact_excluded !== true) errors.push("Hypothetical account must disclose excluded taxes and additional market impact");
if (account.governance?.benchmark_is_market_proxy !== true) errors.push("Hypothetical account must identify SPY as a market proxy");
if (account.governance?.benchmark_fund_expenses_and_distributions_reflected_in_adjusted_close !== true) errors.push("Benchmark adjusted-close treatment is missing");
if (account.governance?.benchmark_initial_trade_cost_excluded !== true) errors.push("Benchmark initial trade-cost exclusion is missing");
if (!/^[a-f0-9]{64}$/.test(account.provenance?.source_sha256 ?? "")) errors.push("Hypothetical account source hash is missing or malformed");
if (!/^[a-f0-9]{64}$/.test(account.provenance?.benchmark_source_sha256 ?? "")) errors.push("Benchmark source hash is missing or malformed");

if (crisis.schema_version !== "1.0") errors.push(`Expected crisis-diversifier schema 1.0; found ${crisis.schema_version}`);
if (crisis.experiment?.status !== "research_candidate") errors.push("Crisis-diversifier artifact is not labeled as a research candidate");
if (crisis.period?.rebalances !== coreResult.num_rebalances) errors.push("Crisis-diversifier rebalance count does not match the release record");
if (crisis.comparator !== "baseline_cash_yield") errors.push("Crisis-diversifier research does not use the governed cash-yield comparator");
if (crisis.verdict?.promotion !== false || (crisis.verdict?.promoted_policies ?? []).length !== 0) errors.push("Crisis-diversifier artifact must preserve the no-promotion verdict");
if ((crisis.acceptance ?? []).length !== 24) errors.push(`Expected 24 crisis-diversifier policy/budget gate rows; found ${(crisis.acceptance ?? []).length}`);
if ((crisis.acceptance ?? []).some((row) => row.all_gates_pass === true)) errors.push("Crisis-diversifier artifact contains a policy that passed despite the no-promotion verdict");
if ((crisis.robustness ?? []).length !== 96) errors.push(`Expected 96 crisis-diversifier cost/budget robustness rows; found ${(crisis.robustness ?? []).length}`);
if ((crisis.bootstrap ?? []).length !== 6) errors.push(`Expected six crisis-diversifier bootstrap comparisons; found ${(crisis.bootstrap ?? []).length}`);
if ((crisis.stress_windows ?? []).length !== 40) errors.push(`Expected 40 crisis-diversifier stress observations; found ${(crisis.stress_windows ?? []).length}`);
const officialCrisisBaseline = (crisis.overall ?? []).find((row) => row.policy === "official_baseline" && row.period === "overall");
for (const key of ["annualized_net_return", "net_sharpe", "max_drawdown"]) {
  if (Math.abs(Number(officialCrisisBaseline?.[key]) - Number(coreResult[key])) > 1e-12) errors.push(`Crisis-diversifier baseline ${key} does not reproduce the release`);
}
for (const key of ["config_sha256", "baseline_source_sha256", "proxy_report_sha256"]) {
  if (!/^[a-f0-9]{64}$/.test(crisis.provenance?.[key] ?? "")) errors.push(`Crisis-diversifier ${key} is missing or malformed`);
}
for (const [pathKey, hashKey] of [["config", "config_sha256"], ["baseline_source", "baseline_source_sha256"], ["proxy_report", "proxy_report_sha256"]]) {
  const relativePath = crisis.provenance?.[pathKey];
  if (!relativePath || !fs.existsSync(path.resolve(ROOT, "..", relativePath))) errors.push(`Crisis-diversifier provenance file is missing: ${relativePath}`);
  else if (repositorySha256(relativePath) !== crisis.provenance?.[hashKey]) errors.push(`Crisis-diversifier provenance hash does not match ${relativePath}`);
}

if (drawdownBudget.schema_version !== "1.0") errors.push(`Expected drawdown-budget schema 1.0; found ${drawdownBudget.schema_version}`);
if (drawdownBudget.experiment?.status !== "validated_research_candidate") errors.push("Drawdown-budget artifact is not labeled as a validated research candidate");
if (drawdownBudget.experiment?.confirmation_segment_pristine !== false) errors.push("Drawdown-budget artifact must disclose that its confirmation segment is not pristine");
if (drawdownBudget.period?.rebalances !== 139) errors.push("Drawdown-budget observation count is not the governed 139-period record");
if (drawdownBudget.acceptance?.all_gates_pass !== true) errors.push("Drawdown-budget candidate did not pass its frozen research gates");
if (Number(drawdownBudget.acceptance?.overall_max_drawdown) < -0.25) errors.push("Drawdown-budget candidate exceeds the 25% research drawdown target");
if (drawdownBudget.verdict?.research_target_achieved !== true) errors.push("Drawdown-budget target-achieved verdict is missing");
if (drawdownBudget.verdict?.promotion !== false || drawdownBudget.verdict?.status !== "validated_candidate") errors.push("Drawdown-budget candidate must not be represented as canonically promoted");
if (drawdownBudget.verdict?.independent_holdout_available !== false || drawdownBudget.verdict?.explicit_release_approval !== false) errors.push("Drawdown-budget release blockers are not disclosed");
if (drawdownBudget.verdict?.shadow_mandate_approved !== true || drawdownBudget.verdict?.explicit_shadow_approval !== true) errors.push("Drawdown-budget shadow approval is not recorded");
if (drawdownBudget.verdict?.soft_floor_is_not_a_guarantee !== true) errors.push("Drawdown-budget soft-floor limitation is missing");
if (Number(drawdownBudget.bootstrap?.candidate_max_drawdown_probability_below_25pct) < 0.95) errors.push("Drawdown-budget bootstrap drawdown gate failed");
const shadowMandate = drawdownBudget.shadow_mandate ?? {};
if (shadowMandate.mandate?.status !== "approved_awaiting_first_eligible_snapshot" || shadowMandate.mandate?.paper_notional_usd !== 100000) errors.push("Drawdown-budget shadow mandate approval state is invalid");
if (shadowMandate.activation?.historical_backfill_permitted !== false || shadowMandate.activation?.current_status !== "awaiting_first_forward_observation") errors.push("Drawdown-budget shadow activation rules are invalid");
for (const key of ["live_capital", "brokerage_connection", "order_generation", "order_submission"]) {
  if (shadowMandate.execution?.[key] !== false) errors.push(`Drawdown-budget shadow execution control ${key} must be false`);
}
if (shadowMandate.execution?.canonical_release_unchanged !== true || shadowMandate.promotion?.automatic_promotion !== false) errors.push("Drawdown-budget shadow mandate must preserve the canonical release and prohibit automatic promotion");
if (shadowMandate.ledger?.observations !== 0) errors.push("Drawdown-budget shadow ledger must begin with zero forward observations");
for (const [pathKey, hashKey] of [["config", "config_sha256"], ["shadow_mandate_config", "shadow_mandate_config_sha256"], ["baseline_source", "baseline_source_sha256"], ["cash_proxy_report", "cash_proxy_report_sha256"], ["result_path", "result_sha256"]]) {
  const relativePath = drawdownBudget.provenance?.[pathKey];
  if (!relativePath || !fs.existsSync(path.resolve(ROOT, "..", relativePath))) errors.push(`Drawdown-budget provenance file is missing: ${relativePath}`);
  else if (repositorySha256(relativePath) !== drawdownBudget.provenance?.[hashKey]) errors.push(`Drawdown-budget provenance hash does not match ${relativePath}`);
}

const releaseRankingStatus = release.data_status?.ranking_snapshot ?? {};
if (releaseRankingStatus.source !== "web/public/data/release_rankings_snapshot.json") errors.push("Release snapshot does not point to the governed 20D ranking artifact");
if (releaseRankingStatus.count !== rankingRows.length) errors.push("Release data-status ranking count is inconsistent");
if (releaseRankingStatus.signal_date !== ranking.latest_signal_state?.date) errors.push("Release data-status ranking date is inconsistent");
if (releaseRankingStatus.model_horizon_days !== 20) errors.push("Release data-status ranking horizon is not 20D");
if (releaseRankingStatus.release_compatible !== true) errors.push("Release ranking artifact is not marked release-compatible");
if (releaseRankingStatus.live !== false) errors.push("Release ranking artifact must be labeled not live");
if (release.data_status?.candidate_snapshot?.count !== candidateRows.length) errors.push("Release data-status candidate count is inconsistent");
if (release.data_status?.candidate_snapshot?.live !== false) errors.push("Candidate artifact must be labeled not live");

const packageJson = JSON.parse(read("package.json"));
for (const script of ["dev", "build", "start", "lint", "validate:site", "smoke", "release:check", "check:deployment"]) {
  if (!packageJson.scripts?.[script]) errors.push(`Missing npm release script: ${script}`);
}
if (!String(packageJson.scripts?.["release:check"] ?? "").includes("validate:site")) errors.push("release:check does not run the static site contract");
if (!String(packageJson.scripts?.["release:check"] ?? "").includes("smoke")) errors.push("release:check does not run the production smoke test");

const siteConfig = read("src/lib/site-config.ts");
for (const route of PRIMARY_NAV_ROUTES) {
  if (!siteConfig.includes(`href: "${route}"`)) errors.push(`Primary navigation does not include ${route}`);
}
if (siteConfig.includes("salarium-ten.vercel.app")) errors.push("Site configuration contains the obsolete hard-coded Vercel URL");

if (errors.length) {
  console.error("SALARIUM_SITE_CONTRACT=FAIL");
  for (const error of errors) console.error(`- ${error}`);
  process.exit(1);
}

console.log("SALARIUM_SITE_CONTRACT=PASS");
console.log(`Routes validated: ${ROUTES.size}`);
console.log(`Source files inspected: ${sourceFiles.length}`);
console.log(`Release rankings: ${rankingRows.length} / ${ranking.latest_signal_state.universe_count}`);
console.log(`Candidates: ${candidateRows.length}`);
