import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "src");
const DATA = path.join(ROOT, "public", "data");

const ROUTES = new Map([
  ["/", "src/app/page.tsx"],
  ["/rankings", "src/app/rankings/page.tsx"],
  ["/candidates", "src/app/candidates/page.tsx"],
  ["/architecture", "src/app/architecture/page.tsx"],
  ["/research", "src/app/research/page.tsx"],
  ["/about", "src/app/about/page.tsx"],
  ["/disclosures", "src/app/disclosures/page.tsx"],
]);

const ALLOWED_INTERNAL = new Set([
  ...ROUTES.keys(),
  "/data/release_snapshot.json",
  "/data/release_rankings_snapshot.json",
  "/data/candidate_funnel_snapshot.json",
  "/salarium-mark.svg",
  "/manifest.webmanifest",
  "/robots.txt",
  "/sitemap.xml",
  "/opengraph-image",
]);

const REQUIRED_ARTIFACTS = [
  "src/app/layout.tsx",
  "src/app/manifest.ts",
  "src/app/robots.ts",
  "src/app/sitemap.ts",
  "src/app/opengraph-image.tsx",
  "src/app/not-found.tsx",
  "src/app/error.tsx",
  "src/app/loading.tsx",
  "public/salarium-mark.svg",
  "public/data/release_snapshot.json",
  "public/data/release_rankings_snapshot.json",
  "public/data/candidate_funnel_snapshot.json",
  "scripts/smoke-site.mjs",
  "scripts/check-deployment.mjs",
  "../docs/SALARIUM_1_0_MODEL_CARD.md",
  "../docs/RELEASE_NOTES_1_0.md",
];

const FORBIDDEN = [
  ["create next app", "starter scaffold"],
  ["generated by create next app", "starter scaffold"],
  ["href=\"#\"", "placeholder hash link"],
  ["href='#'", "placeholder hash link"],
  ["href=\"\"", "empty link"],
  ["href=''", "empty link"],
  ["javascript:", "javascript link"],
  ["lorem ipsum", "placeholder copy"],
  ["coming soon", "unfinished copy"],
  ["todo", "unfinished TODO"],
  ["fixme", "unfinished FIXME"],
  ["solarium", "legacy product branding"],
];

function walk(directory) {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(directory, entry.name);
    if (entry.isDirectory()) return walk(full);
    return [full];
  });
}

function read(relative) {
  return fs.readFileSync(path.join(ROOT, relative), "utf8");
}

function readJson(filename) {
  return JSON.parse(fs.readFileSync(path.join(DATA, filename), "utf8"));
}

function relative(filename) {
  return path.relative(ROOT, filename).split(path.sep).join("/");
}

function normalizeInternal(raw) {
  const withoutHash = raw.split("#", 1)[0];
  return withoutHash.split("?", 1)[0] || "/";
}

const errors = [];

for (const [route, relativePage] of ROUTES) {
  const filename = path.join(ROOT, relativePage);
  if (!fs.existsSync(filename)) {
    errors.push(`Missing page for ${route}: ${relativePage}`);
    continue;
  }
  if (!fs.readFileSync(filename, "utf8").includes('id="main-content"')) {
    errors.push(`Route ${route} does not expose id=\"main-content\" for the skip link`);
  }
}

for (const artifact of REQUIRED_ARTIFACTS) {
  if (!fs.existsSync(path.join(ROOT, artifact))) errors.push(`Missing release artifact: ${artifact}`);
}

const sourceFiles = walk(SRC).filter((filename) => /\.(?:ts|tsx|css)$/.test(filename));
for (const filename of sourceFiles) {
  const text = fs.readFileSync(filename, "utf8");
  const lower = text.toLowerCase();

  for (const [token, label] of FORBIDDEN) {
    if (lower.includes(token)) errors.push(`${relative(filename)} contains ${label}: ${JSON.stringify(token)}`);
  }

  for (const match of text.matchAll(/(?:href|canonical)\s*[:=]\s*(?:\{\s*)?["'](\/[^"']*)["']/g)) {
    const destination = normalizeInternal(match[1]);
    if (!ALLOWED_INTERNAL.has(destination)) {
      errors.push(`${relative(filename)} links to an unresolved internal destination: ${match[1]}`);
    }
  }

  for (const match of text.matchAll(/<button\b[^>]*>/gs)) {
    if (!/\bonClick\s*=/.test(match[0])) {
      errors.push(`${relative(filename)} contains a button without an onClick handler: ${match[0].replace(/\s+/g, " ").slice(0, 160)}`);
    }
  }
}

const release = readJson("release_snapshot.json");
const ranking = readJson("release_rankings_snapshot.json");
const candidates = readJson("candidate_funnel_snapshot.json");

if (release.schema_version !== "1.1") errors.push(`Expected release schema 1.1; found ${release.schema_version}`);
const architecture = release.architecture ?? {};
const lockedArchitecture = {
  universe: "Liquid-500",
  model_horizon_days: 20,
  rebalance_every_days: 10,
  top_n: 10,
  buffer_rank: 15,
  covariance_lookback_days: 60,
  signal_blend: 0.25,
  leverage_cap: 1.25,
};
for (const [key, expected] of Object.entries(lockedArchitecture)) {
  if (architecture[key] !== expected) errors.push(`Release architecture ${key} is ${architecture[key]}; expected ${expected}`);
}
if (release.governance?.live_trading !== false) errors.push("Release must explicitly state that live trading is disabled");
if (release.governance?.investment_advice !== false) errors.push("Release must explicitly state that it is not investment advice");
if (!Array.isArray(release.research?.decisions) || release.research.decisions.length !== 6) {
  errors.push("Release decision ledger must contain six governed decisions");
}

if (ranking.schema_version !== "1.0") errors.push(`Expected ranking schema 1.0; found ${ranking.schema_version}`);
if (ranking.architecture?.universe !== "Liquid-500") errors.push("Release ranking universe is not Liquid-500");
if (ranking.architecture?.model_horizon_days !== 20) errors.push("Release rankings are not generated by the 20D model");
if (ranking.architecture?.rebalance_every_days !== 10) errors.push("Release ranking artifact does not declare the 10D rebalance cadence");
const rankingRows = ranking.latest_signal_state?.rankings ?? [];
if (ranking.latest_signal_state?.count !== rankingRows.length) errors.push("Release ranking count does not match the published row count");
if ((ranking.latest_signal_state?.universe_count ?? 0) < rankingRows.length) errors.push("Release ranking universe count is smaller than the published ranking list");
if (rankingRows.length !== 25) errors.push(`Expected 25 published release rankings; found ${rankingRows.length}`);
const ranks = rankingRows.map((row) => Number(row.rank));
if (ranks.some((value, index) => value !== index + 1)) errors.push("Release rankings are not numbered consecutively from 1");
const scores = rankingRows.map((row) => Number(row.score));
if (scores.some((value, index) => index > 0 && value > scores[index - 1])) errors.push("Release rankings are not sorted by descending score");

const candidateRows = candidates.candidates ?? [];
if (candidates.evidence_summary?.candidate_count !== candidateRows.length) errors.push("Candidate snapshot count does not match candidate rows");

const releaseRankingStatus = release.data_status?.ranking_snapshot ?? {};
if (releaseRankingStatus.source !== "web/public/data/release_rankings_snapshot.json") errors.push("Release snapshot does not point to the governed 20D ranking artifact");
if (releaseRankingStatus.count !== rankingRows.length) errors.push("Release data-status ranking count is inconsistent");
if (releaseRankingStatus.signal_date !== ranking.latest_signal_state?.date) errors.push("Release data-status ranking date is inconsistent");
if (releaseRankingStatus.model_horizon_days !== 20) errors.push("Release data-status ranking horizon is not 20D");
if (releaseRankingStatus.release_compatible !== true) errors.push("Release ranking artifact is not marked release-compatible");
if (releaseRankingStatus.live !== false) errors.push("Release ranking artifact must be labeled not live");
if (release.data_status?.candidate_snapshot?.count !== candidateRows.length) errors.push("Release data-status candidate count is inconsistent");
if (release.data_status?.candidate_snapshot?.live !== false) errors.push("Candidate artifact must be labeled not live");

const packageJson = JSON.parse(read("package.json"));
for (const script of ["dev", "build", "start", "lint", "validate:site", "smoke", "release:check", "check:deployment"]) {
  if (!packageJson.scripts?.[script]) errors.push(`Missing npm release script: ${script}`);
}
if (!String(packageJson.scripts?.["release:check"] ?? "").includes("validate:site")) errors.push("release:check does not run the static site contract");
if (!String(packageJson.scripts?.["release:check"] ?? "").includes("smoke")) errors.push("release:check does not run the production smoke test");

const siteConfig = read("src/lib/site-config.ts");
for (const route of ROUTES.keys()) {
  if (route === "/disclosures") continue;
  if (!siteConfig.includes(`href: "${route}"`)) errors.push(`Primary navigation does not include ${route}`);
}
if (siteConfig.includes("salarium-ten.vercel.app")) errors.push("Site configuration contains the obsolete hard-coded Vercel URL");

if (errors.length) {
  console.error("SALARIUM_SITE_CONTRACT=FAIL");
  for (const error of errors) console.error(`- ${error}`);
  process.exit(1);
}

console.log("SALARIUM_SITE_CONTRACT=PASS");
console.log(`Routes validated: ${ROUTES.size}`);
console.log(`Source files inspected: ${sourceFiles.length}`);
console.log(`Release rankings: ${rankingRows.length} / ${ranking.latest_signal_state.universe_count}`);
console.log(`Candidates: ${candidateRows.length}`);
