import type { Metadata } from "next";
import ArchitectureExplorer, { type ArchitectureModule } from "@/components/architecture-explorer";
import { PageIntro } from "@/components/ui";
import { percent } from "@/lib/format";
import { loadReleaseSnapshot } from "@/lib/site-data";

export const metadata:Metadata={title:"Architecture",description:"Explore Salarium's governed equity research architecture, inputs, outputs, configuration, experiments, and source provenance.",alternates:{canonical:"/architecture"}};
export default function ArchitecturePage(){const release=loadReleaseSnapshot();const a=release.architecture;const generated=release.generated_at_utc;const modules:ArchitectureModule[]=[
  {index:"01",title:"Universe",summary:a.universe,purpose:"Defines the eligible research population before any model score is produced.",inputs:"Liquidity and security eligibility policy",outputs:"Governed 500-security cross-sections",methodology:"Canonical Liquid-500 snapshot governance",configuration:a.universe,experiment:"Broad versus Liquid-500 walk-forward comparison",source:"src/universe/liquid_universe.py",artifact:"reports/experiments/broad_vs_liquid500_walkforward.csv",generated},
  {index:"02",title:"Feature Engine",summary:"Technical, macro, risk",purpose:"Builds temporally valid model inputs from governed market and macro data.",inputs:"Point-in-time price, liquidity, macro, and regime inputs",outputs:"Model-safe feature rows",methodology:"Feature policy plus temporal-integrity checks",configuration:"Repository feature policy; exact active columns remain artifact-defined",experiment:"Macro feature audit and leakage review",source:"src/features/liquid500_features.py",artifact:"reports/data_quality_leakage_latest.md",generated},
  {index:"03",title:"Alpha Model",summary:`${a.model_horizon_days}D prediction`,purpose:"Produces annual expanding-window out-of-sample cross-sectional scores.",inputs:"Model-safe features and forward-return target",outputs:"Ticker-level 20D ranking scores",methodology:"Annual expanding-window walk-forward prediction",configuration:`${a.model_horizon_days}-trading-day target`,experiment:"Horizon and rebalance tournament",source:"scripts/generate_horizon_walkforward_scores.py",artifact:"results/horizon_walkforward/horizon_20d/walkforward_oos_scores.csv",generated},
  {index:"04",title:"Ranking Engine",summary:"Cross-sectional scoring",purpose:"Orders each governed universe snapshot by comparable model score.",inputs:"Out-of-sample scores",outputs:"Rank, score percentile, risk context",methodology:"Descending cross-sectional ranking",configuration:`${a.universe}; ${a.rebalance_every_days}D portfolio cadence`,experiment:"Universe and horizon comparisons",source:"scripts/export_release_rankings.py",artifact:"web/public/data/release_rankings_snapshot.json",generated},
  {index:"05",title:"Selection",summary:`Top-${a.top_n} + rank-${a.buffer_rank}`,purpose:"Concentrates signal while limiting turnover around the entry boundary.",inputs:"Current ranking and prior selection state",outputs:"Selected portfolio candidate set",methodology:"Top-N selection with persistence buffer",configuration:`Top-${a.top_n}; rank-${a.buffer_rank} buffer`,experiment:"Portfolio breadth research",source:"src/backtesting/walkforward_rank_backtest.py",artifact:"reports/experiments/portfolio_breadth_static.csv",generated},
  {index:"06",title:"Portfolio Engine",summary:`${a.covariance_lookback_days}D shrinkage`,purpose:"Balances joint covariance risk with controlled model conviction.",inputs:"Selected names, returns, covariance, scores",outputs:"Long-only normalized security weights",methodology:"Ledoit-Wolf maximum diversification plus signal blend",configuration:`${a.covariance_lookback_days}D; ${percent(1-a.signal_blend,0)} risk / ${percent(a.signal_blend,0)} signal`,experiment:"Covariance and signal-aware weighting tournaments",source:"scripts/evaluate_signal_aware_covariance.py",artifact:"reports/experiments/signal_aware_covariance_overall.csv",generated},
  {index:"07",title:"Risk Engine",summary:"Regime, drawdown, exposure",purpose:"Controls total portfolio exposure after security weights are formed.",inputs:"Risk state, drawdown, portfolio volatility",outputs:"Governed portfolio exposure",methodology:"Regime and drawdown-aware exposure policy",configuration:`Hard ceiling ${a.leverage_cap.toFixed(2)}x`,experiment:"Horizon/exposure and leverage research",source:"src/backtesting/risk_controls.py",artifact:"reports/experiments/horizon_exposure_robustness_summary.csv",generated},
  {index:"08",title:"Final Portfolio",summary:`${percent(a.max_single_name_weight,0)} name cap`,purpose:"Represents the final governed research portfolio when a release-aligned artifact is exported.",inputs:"Normalized weights and exposure multiplier",outputs:"Holdings, weights, exposure, provenance",methodology:"Long-only constrained research portfolio",configuration:`${percent(a.max_single_name_weight,0)} maximum position; ${a.leverage_cap.toFixed(2)}x ceiling`,experiment:"Selected release configuration",source:"scripts/export_release_snapshot.py",artifact:"Current holdings artifact unavailable",generated:"Not generated"},
];return <main id="main-content" className="site-main"><section className="page-section"><PageIntro eyebrow="SYSTEM ARCHITECTURE" title="Eight modules." muted="One inspectable chain." description="Focus or select a module to inspect its purpose, inputs, outputs, method, current configuration, experiment evidence, and repository source."/><div className="mt-10"><ArchitectureExplorer modules={modules}/></div></section></main>}
