import type { Metadata } from "next";
import { AnnualPerformanceTable } from "@/components/research-visuals";
import ProvenanceDisclosure from "@/components/provenance-disclosure";
import { MetricCard, PageIntro, StatusBadge } from "@/components/ui";
import { number, percent } from "@/lib/format";
import { loadDrawdownBudgetResearch, loadForwardPaperSnapshot, loadReleaseSnapshot } from "@/lib/site-data";

export const metadata: Metadata = { title: "Historical results", description: "Review Salarium's simulated results, yearly returns, drawdowns, and paper account data.", alternates: { canonical: "/research/performance" } };
export default function PerformancePage() { const release=loadReleaseSnapshot(); const riskControl=loadDrawdownBudgetResearch(); const forward=loadForwardPaperSnapshot(); const paper=forward.status==="available"?forward.data:null; const core=release.results.core_balanced; const controlled=riskControl.overall.find((row)=>row.record==="selected"&&row.period==="overall"); const comparator=riskControl.overall.find((row)=>row.record==="cash_yield_comparator"&&row.period==="overall"); if(!controlled||!comparator) throw new Error("Drawdown-budget research artifact is incomplete"); return <main id="main-content" className="site-main"><section className="page-section"><PageIntro eyebrow="HISTORICAL TEST / PAPER TRACKING" title="What the tests returned" muted="And how much risk they took." description="These figures come from annual out-of-sample simulations and separate paper accounts. Modeled costs are included where stated; the results are not live investment performance." />
  <div className="mt-10 grid gap-px bg-white/10 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="ANNUALIZED NET RETURN" value={percent(core.annualized_net_return)} detail="simulated, after modeled costs" /><MetricCard label="NET SHARPE" value={number(core.net_sharpe)} detail="full historical simulation" /><MetricCard label="NET SORTINO" value={number(core.net_sortino)} detail="return relative to downside swings" /><MetricCard label="MAXIMUM DRAWDOWN" value={percent(core.max_drawdown)} detail="simulated peak to trough" tone="negative" /><MetricCard label="AVERAGE EXPOSURE" value={`${core.avg_exposure.toFixed(3)}x`} detail="average invested exposure" /><MetricCard label="ANNUAL TURNOVER" value={`${core.annualized_turnover.toFixed(2)}x`} detail="modeled yearly trading" /><MetricCard label="AVG TRANSACTION COST" value={percent(core.avg_transaction_cost, 3)} detail="modeled per rebalance" /><MetricCard label="EVALUATION PERIOD" value={release.research.period} detail={`${core.num_rebalances} rebalances`} /></div>
  <section className="mt-14 border border-emerald-300/20 bg-emerald-300/[0.025] p-6 sm:p-8" aria-labelledby="risk-control-candidate"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="roman-inscription">DRAWDOWN RULE / PAPER ACCOUNT</p><h2 id="risk-control-candidate" className="mt-4 text-3xl">A separate test of the drawdown rule</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-white/48">The rule cuts stock exposure as the account falls below its previous high. In the historical test, it kept the largest drawdown below 25% without changing the rankings or stock selection. It is approved for paper tracking only; it cannot trade or prevent a sudden gap down.</p></div><StatusBadge tone="positive">{paper?"PAPER ACTIVE":"SHADOW APPROVED"}</StatusBadge></div><div className="mt-8 grid gap-px bg-white/10 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="PAPER TEST DRAWDOWN" value={percent(controlled.max_drawdown)} detail={`${percent(comparator.max_drawdown)} cash-yield comparator`} tone="positive" /><MetricCard label="PAPER TEST RETURN" value={percent(controlled.annualized_net_return)} detail={`${percent(riskControl.acceptance.overall_return_retention)} of comparator`} /><MetricCard label="PAPER TEST SHARPE" value={number(controlled.net_sharpe)} detail={`${riskControl.acceptance.overall_sharpe_delta>=0?"+":""}${riskControl.acceptance.overall_sharpe_delta.toFixed(3)} vs comparator`} /><MetricCard label="PAPER ACCOUNT" value={new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(paper?.forward_portfolio.indicative_nav??riskControl.shadow_mandate.mandate.paper_notional_usd)} detail={paper?`${percent(paper.forward_portfolio.shadow_equity_exposure,0)} equity · ${paper.forward_portfolio.completed_intervals} completed intervals`:"awaiting first forward snapshot"} tone="positive" /></div><p className="mt-6 text-xs leading-6 text-white/35">The account reduces exposure below {percent(riskControl.selected_policy.floor_ratio,0)} of its prior high. The {riskControl.bootstrap.iterations.toLocaleString()}-path bootstrap is a simulation, not a guarantee. Earlier simulated results were not added to the paper account. The confirmation period was not an untouched holdout, and this rule cannot prevent sudden losses. The core release results above use different settings.</p></section>
  <section className="mt-14"><p className="eyebrow">ANNUAL RECORD</p><h2 className="mt-4 text-3xl">Year-by-year historical results</h2><div className="mt-6"><AnnualPerformanceTable core={release.research.yearly.core_balanced} aggressive={release.research.yearly.aggressive} defensive={release.research.yearly.defensive} /></div></section>
  <div className="research-disclosure mt-10"><strong>About these results</strong><p>These are simulated historical results, with modeled trading costs where stated. They are not live investment returns. Because the settings were chosen after testing historical data, the results may overstate future performance.</p><p>The home page shows how the same simulated results would have changed a hypothetical $100,000 account, beside SPY over the same dates. The table below shows each year separately.</p></div>
  <div className="mt-8"><ProvenanceDisclosure record={{source:"Salarium release research",artifact:release.provenance.source_report,outOfSamplePeriod:release.research.period,portfolio:"Core balanced",model:`${release.architecture.model_horizon_days}D expanding-window`,commit:release.provenance.git_commit,generatedAt:release.generated_at_utc}} /></div>
  </section></main>; }
