import Link from "next/link";

import { EdgeGlyph } from "@/components/edge-glyph";
import ProvenanceDisclosure from "@/components/provenance-disclosure";
import { DisclosurePanel, InternalCta, MetricCard, SectionHeading, StatusBadge } from "@/components/ui";
import { formatDate, number, percent } from "@/lib/format";
import { loadRankingSnapshot, loadReleaseSnapshot } from "@/lib/site-data";

export default function HomePage() {
  const release=loadReleaseSnapshot(); const ranking=loadRankingSnapshot(); const a=release.architecture; const core=release.results.core_balanced;
  return <main id="main-content" className="site-main">
    <section className="hero-shell"><div className="site-container hero-grid"><div><p className="eyebrow text-emerald-300">Institutional-style research workflow, built in public.</p><h1>Systematic equity research, <span>from signal to portfolio.</span></h1><p className="hero-copy">Salarium ranks a liquid equity universe, constructs concentrated portfolios, models covariance and risk, and governs exposure through a transparent walk-forward research process.</p><div className="mt-8 flex flex-wrap gap-3"><InternalCta href="/rankings">Explore Rankings</InternalCta><InternalCta href="/methodology" secondary>Inspect Methodology</InternalCta></div><p className="hero-disclaimer">RESEARCH SYSTEM · SIMULATED EVIDENCE · NO LIVE EXECUTION</p></div><aside className="system-status" aria-label="Current Salarium research system status"><header><span>SALARIUM / RESEARCH SYSTEM</span><i>COMMITTED SNAPSHOT</i></header><div className="system-status-mark"><EdgeGlyph title="Salarium Imperial Edge Glyph" /><p>MARKET-EDGE RING / PROPRIETARY SIGNAL MARK</p></div><dl><div><dt>Model</dt><dd>{a.model_horizon_days}D</dd></div><div><dt>Universe</dt><dd>{a.universe.toUpperCase()}</dd></div><div><dt>Release</dt><dd>{release.release.version}</dd></div><div><dt>Snapshot</dt><dd>{formatDate(ranking.latest_signal_state.date)}</dd></div><div className="system-status-state"><dt>Status</dt><dd><span />Committed / not live</dd></div></dl></aside></div></section>
    <section className="configuration-strip" aria-label="Current research configuration"><div className="site-container">{[[`${a.model_horizon_days}D`,"alpha horizon"],[`${a.rebalance_every_days}D`,"rebalance"],[String(ranking.latest_signal_state.universe_count),"research universe"],[String(a.top_n),"portfolio positions"],[`${a.leverage_cap.toFixed(2)}x`,"hard exposure ceiling"]].map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section>
    <section className="site-container site-section"><SectionHeading eyebrow="HOW SALARIUM THINKS" title="A governed chain, not a black box." description="Each stage has a narrow responsibility, an inspectable output, and a downstream control." /><div className="pipeline-row">{[["01","Universe","Liquid-500"],["02","Alpha","20D OOS scores"],["03","Rank","Cross-sectional order"],["04","Select","Top-10 + buffer"],["05","Construct","Covariance + signal"],["06","Govern","Exposure + limits"]].map(([index,title,detail])=><div key={index}><span>{index}</span><strong>{title}</strong><small>{detail}</small></div>)}</div></section>
    <section className="section-rule"><div className="site-container site-section"><SectionHeading eyebrow="LATEST RANKING SNAPSHOT" title="The current model output, in context." description={`Signal date ${formatDate(ranking.latest_signal_state.date)}. Top 5 of 25 published rows from a ${ranking.latest_signal_state.universe_count}-security cross-section.`} action={<InternalCta href="/rankings" secondary>Open Rankings</InternalCta>} /><div className="ranking-preview">{ranking.latest_signal_state.rankings.slice(0,5).map((row)=><Link href="/rankings" key={row.ticker}><span>{String(row.rank).padStart(2,"0")}</span><strong>{row.ticker}</strong><em>{row.score.toFixed(6)}</em><small>{percent(row.score_percentile,1)}</small></Link>)}</div></div></section>
    <section className="site-container site-section"><SectionHeading eyebrow="SELECTED OUT-OF-SAMPLE EVIDENCE" title="Evidence with the risk attached." description="Annual expanding-window research over the committed 2021–2026 record. Historical simulation, not live performance." /><div className="grid gap-px bg-white/10 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="ANNUALIZED NET RETURN" value={percent(core.annualized_net_return)} detail="simulated, modeled costs" /><MetricCard label="NET SHARPE" value={number(core.net_sharpe)} detail="core balanced candidate" /><MetricCard label="MAXIMUM DRAWDOWN" value={percent(core.max_drawdown)} detail="simulated peak to trough" tone="negative" /><MetricCard label="AVERAGE EXPOSURE" value={`${core.avg_exposure.toFixed(3)}x`} detail="governed research exposure" /></div><div className="mt-6"><InternalCta href="/research/performance" secondary>Inspect Performance</InternalCta></div></section>
    <section className="section-rule"><div className="site-container site-section"><SectionHeading eyebrow="EXPERIMENT RECORD" title="Rejected ideas remain visible." description="The release was shaped by controlled comparisons, including ideas that sounded attractive and did not survive the evidence." /><div className="grid gap-4 md:grid-cols-3">{release.research.decisions.slice(0,3).map((decision)=><article className="evidence-card" key={decision.key}><StatusBadge tone={decision.status==="rejected"?"negative":"positive"}>{decision.status.toUpperCase()}</StatusBadge><h3>{decision.title}</h3><p>{decision.finding}</p><small>{decision.source_report}</small></article>)}</div><div className="mt-6"><InternalCta href="/research/experiments" secondary>Open Experiment Archive</InternalCta></div></div></section>
    <section className="site-container site-section"><div className="split-feature"><div><p className="eyebrow">METHODOLOGY</p><h2>Configuration is inspectable.</h2><p>Prediction horizon, cadence, breadth, covariance estimator, signal influence, position caps, and exposure limits are published with their evidence boundaries.</p><InternalCta href="/methodology" secondary>Read Methodology</InternalCta></div><dl>{[["Validation","Expanding-window OOS"],["Covariance",`${a.covariance_lookback_days}D Ledoit-Wolf`],["Weighting",`${percent(1-a.signal_blend,0)} risk / ${percent(a.signal_blend,0)} signal`],["Position cap",percent(a.max_single_name_weight,0)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div></section>
    <section className="section-rule"><div className="site-container site-section"><SectionHeading eyebrow="ARCHITECTURE + PROVENANCE" title="Every claim points back to an artifact." description="The system separates universe, feature, alpha, ranking, selection, portfolio, and risk responsibilities." /><div className="grid gap-4 lg:grid-cols-[1fr_.8fr]"><div className="architecture-mini">{["Universe","Feature engine","Alpha model","Ranking engine","Selection","Portfolio engine","Risk engine","Final portfolio"].map((item,index)=><span key={item}><i>{String(index+1).padStart(2,"0")}</i>{item}</span>)}</div><ProvenanceDisclosure record={{source:"Governed release snapshot",artifact:release.provenance.source_report,outOfSamplePeriod:release.research.period,portfolio:"Core balanced",model:`${a.model_horizon_days}D expanding-window`,commit:release.provenance.git_commit,generatedAt:release.generated_at_utc}} /></div><div className="mt-6"><InternalCta href="/architecture" secondary>Explore Architecture</InternalCta></div></div></section>
    <section className="site-container site-section"><DisclosurePanel items={["Simulated historical results do not represent live investment performance.","Modeled costs do not capture every tax, market-impact, financing, or capacity constraint.","Iterative research creates model-selection bias even when evaluation is walk-forward.","Data quality, universe selection, covariance estimation, and regime change remain material risks."]} /></section>
  </main>;
}
